name: Build

on:
  pull_request:
    branches:
      - '*'

env:
  CACHE_EPOCH: 3

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILDING_IN_CI: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build dist
        uses: ./.github/actions/build-dist
      - name: Unzip
        shell: bash
        run: tar zxvf ./dist/jupyterlite-app-0.1.0-beta.17.tgz
      - name: Copy contents
        shell: bash
        run: cp -r ./contents/* ./package
